---
title: "R Notebook"
output: html_notebook
---
```{r}
library(tidyverse)
library(lme4)
library(sjPlot)
library(ggplot2)
library(lmerTest)
```
---
```{r}
data <- read.csv("D:\\Desktop\\all_data_02_2019-2.csv", sep = ";", encoding = "UTF-8")
metadata <- read.csv("D:\\Desktop\\metadata_basic.csv", sep = ";", encoding = "UTF-8")

data %>%
  count(realization)


colnames(metadata) -> x

x[1] <- "speaker"

colnames(metadata) <- x

levels(data$speaker)<-levels(metadata$speaker)

data <- data[data$realization != "?", ]
data <- data[data$realization != "се?", ]
data <- data[data$realization != "ся?", ]
data <- data[data$realization != "0", ]
data <- data[data$realization != "си", ]

inner_join(data, metadata, by = "speaker") %>%
  select(speaker, Sex, Year.of.birth, realization) -> new_data
```

```{r}
new_data %>%
  group_by(speaker) %>%
  mutate(utterances = n()) %>%
  group_by(speaker, realization) %>%
  mutate(sep_utterances = n()) %>%
  unique() %>%
  filter(Year.of.birth > 0) %>%
  spread(key = "realization", value = "sep_utterances") -> new_data.2

colnames(new_data.2) -> x
x[5] <- "dial"
x[6] <- "std"
colnames(new_data.2) <- x

new_data.2 %>%
  mutate(dial = ifelse(is.na(dial), 0, dial), std = ifelse(is.na(std), 0, std)) %>%
  mutate(dial_perc = dial / utterances) -> new_data.2
```

```{r}
# fixed
f0 <- lmer(data = new_data, as.numeric(realization) ~ Year.of.birth + Sex + (1|speaker))
summary(f0)
plot_model(f0, type = "pred", terms = c("Sex", "Year.of.birth"))

# random intercept
f1 <- lmer(data = new_data, as.numeric(realization) ~ Year.of.birth + (1|Sex) + (1|speaker))
summary(f1)
plot_model(f1, type = "pred", terms = c("Sex", "Year.of.birth"))

# random slope with correlated intercept
f2 <- lmer(data = new_data, as.numeric(realization) ~ Year.of.birth + (1|speaker) + (Sex|Year.of.birth))
summary(f2)
plot_model(f2, type = "pred", terms = c("Sex", "Year.of.birth"))

# random slope with no variation in intercept
f2.2 <- lmer(data = new_data, as.numeric(realization) ~ Year.of.birth + (1|speaker) + (0+Sex|Year.of.birth))
summary(f2.2)
plot_model(f2.2, type = "pred", terms = c("Sex", "Year.of.birth"))

# uncorrelated random intercept and random slope within group
f3 <- lmer(data = new_data, as.numeric(realization) ~ (1|speaker) + (1|Year.of.birth) + (0+Sex|Year.of.birth))
summary(f3)
plot_model(f3, type = "pred", terms = c("Sex", "Year.of.birth"))
```

```{r}

new_data.2 %>%
  ggplot(., aes(x = Year.of.birth, y = dial_perc, size = dial, color = Sex)) + 
  geom_point() +
  geom_smooth(method = "glm", aes(x = Year.of.birth, y = dial_perc),
    method.args = list(family = "binomial"), 
    se = TRUE)
```